source 'https://rubygems.org'
#gem 'rack', '~>1.3.5'
gem 'rack'
gem 'mustache', :require => 'mustache'
gem 'sinatra'
# http://www.sinatrarb.com/contrib
gem 'sinatra-contrib'
# internationalization
gem 'r18n-core'
gem 'sinatra-r18n', :require => 'sinatra/r18n'
gem 'activesupport', :require => 'activesupport/all'
gem 'mongo'
gem 'bson'
gem 'bson_ext'
gem 'mongoid', github: 'mongoid/mongoid'
gem 'mongoid-grid_fs'
gem 'coffee-script'
gem 'sass'

group :development, :test do
  gem 'httparty'
  gem 'nokogiri'
  gem 'unicode_utils'
  gem 'typhoeus'
  gem 'shotgun'
  gem 'rspec'
  gem 'roo'
  gem 'spreadsheet'
  gem 'colored'
end